USE [master]
GO

/****** Object:  Database [RavenClausBangazon]    Script Date: 4/8/2017 11:27:46 AM ******/
CREATE DATABASE [RavenClausBangazon]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RavenClausBangazon', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\RavenClausBangazon.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RavenClausBangazon_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\RavenClausBangazon_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RavenClausBangazon] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RavenClausBangazon].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RavenClausBangazon] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET ARITHABORT OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RavenClausBangazon] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RavenClausBangazon] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RavenClausBangazon] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RavenClausBangazon] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RavenClausBangazon] SET  MULTI_USER 
GO

ALTER DATABASE [RavenClausBangazon] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RavenClausBangazon] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RavenClausBangazon] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RavenClausBangazon] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RavenClausBangazon] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RavenClausBangazon] SET  READ_WRITE 
GO

